packages:
  - "apps/*"
  - "packages/*"

catalog:
  'next': '^15.1.6'
  'react': '^19.0.0'
  'react-dom': '^19.0.0'
  'drizzle-orm': '^0.39.3'

  'typescript': '^5.7.3'
  '@types/node': '^22'
  '@types/react': '^19.0.8'
  '@types/react-dom': '^19.0.3'