packages:
  - "apps/*"
  - "packages/*"

catalog:
  'next': '^15.1.6'
  'react': '^19.0.0'
  'react-dom': '^19.0.0'
  'drizzle-orm': '^0.39.3'
  "@supabase/auth-js": "^2.68.0"
  "@supabase/ssr": "^0.5.2"
  "@supabase/supabase-js": "^2.48.1"
  "@tanstack/react-query": "^5.66.3"
  "@tanstack/react-query-devtools": "^5.66.3"

  'typescript': '^5.7.3'
  '@types/node': '^22'
  '@types/react': '^19.0.8'
  '@types/react-dom': '^19.0.3'